### ISSUE TITLE
[Discussion] Extraneous details make training take too long

### ISSUE THREAD

**Issue by jmmastey** [jmmastey/level_up_exercises#677]
Per discussion with @djkotowski and @bwthomas, they're looking at ways to pare down some of the assignments. Since we don't want to remove learning, that means trimming some of the non-essential parts of assignments.

As an example, overlord currently requires you to build a bomb. Since the assignment is about BDD, that detail is not really necessary, and often trips up learners.

Here's a potential suggestion to change and remove that requirement:
https://github.com/jmmastey/level_up_exercises/compare/make_overlord_shorter

**Comment by jmmastey** [comment]
Looking for discussion on whether this is a smart change in general, and whether that change in particular is a good move. I've also got my eyes on data_science, which is the shittiest of the assignments by far.

**Comment by ashtonthomas** [comment]
I'm definitely in favor of this. I am guilty of putting more weight on the wrong things while reviewing this exercise.

**Comment by ashtonthomas** [comment]
However, I'm not sure how this helps force people to write tests first if we are giving them the code (?) Then again, doing TDD/BDD with tests first was impossible for me until I become familiar with the DSL of test tools, which took a lot of iterations. So teaching testing first is just hard (when there is no background of testing). The proposed change is probably good, though.

**Comment by djkotowski** [comment]
The TDD will be the previous exercise (currently Data Science).  Overlord will focus on BDD.

**Comment by djkotowski** [comment]
Overlord changes merged: #895

**Comment by danvayn** [comment]
Providing a starting node or rails app for pmail would be a good next step.

**Comment by jmmastey** [comment]
Closing this as it's quite old. Feel free to re-open.
